site_name: NGX
site_description: Parsing configuration library
site_author: Haiker
site_url: https://ihaiker.github.io/ngx
repo_url: https://github.com/ihaiker/ngx
copyright: Copyright @2021 Haiker

nav:
  - 简介: index.md
  - 功能特性:
      - "解析配置文件": parse.md
      - "Marshal/Unmarshal": marshal.md
      - "配置查询语言PQL": pql.md
      - "后置hook": hooks.md
      - "命令行工具": cli.md
      - "转为JSON": json.md
  - 版本历史: versions/index.md

theme: readthedocs

extra_css:
  - extra.css
