name: auto-release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: auto-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          stable: false
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: test codes
        run: |
          go mod download
          go test ./...

      - name: Build project
        run: sh -c ./build.sh

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "(.*)"

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release-${{steps.tagName.outputs.tag}}"

      - name: Read release commits
        id: release_docs
        uses: juliangruber/read-file-action@v1
        with:
          path: ./docs/versions/${{ steps.tagName.outputs.tag }}.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          release_name: Release ${{ steps.tagName.outputs.tag }}
          body: ${{ steps.release_docs.outputs.content }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: bin/dist
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_paths: ./bin/dist/*
